server {
    listen ${PORT};
    client_max_body_size 100M;

    root /usr/share/nginx/html;
    index index.html;

    # Serve React SPA - all routes go to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}